"""add step and step_progress to analyses

Revision ID: 3aad3c52ed63
Revises: 20260410_0001
Create Date: 2026-04-10 15:32:03.863301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3aad3c52ed63'
down_revision: Union[str, None] = '20260410_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('step', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('analyses', sa.Column('step_progress', sa.JSON(), nullable=False, server_default='{}'))
    # 기존 completed/failed 레코드의 step을 status에 맞춰 설정
    op.execute("UPDATE analyses SET step = status")
    op.alter_column('analysis_results', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_constraint('mentions_content_hash_key', 'mentions', type_='unique')
    op.drop_index('ix_mentions_content_hash', table_name='mentions')
    op.create_index(op.f('ix_mentions_content_hash'), 'mentions', ['content_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentions_content_hash'), table_name='mentions')
    op.create_index('ix_mentions_content_hash', 'mentions', ['content_hash'], unique=False)
    op.create_unique_constraint('mentions_content_hash_key', 'mentions', ['content_hash'])
    op.alter_column('analysis_results', 'content',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('analyses', 'step_progress')
    op.drop_column('analyses', 'step')
    # ### end Alembic commands ###
